### ISSUE TITLE
User can view a post content feed

### ISSUE THREAD

**Issue by richiebotteri** [richiebotteri/2022-11_JS-2_CA_Repo#20]
### To-do

- [ ] Create a function that can fetch post with GET request
- [ ] Display all user posts on homepage
- [ ] Display post from logged in user on profile page
